// Sample vehicle data for seeding
const vehicles = [
  {
    name: "Porsche 911",
    image: "/cars/image 1.png",
    price: 865000,
    oldPrice: 900000,
    transmission: "Số tự động",
    seats: 2,
    fuel: "Dầu Diesel",
    location: "Quận Sơn Trà, Đà Nẵng",
    rating: 5.0,
    trips: 37,
    description: "Xe thể thao hiệu suất cao, phù hợp cho trải nghiệm tốc độ.",
    badge: "37 chuyến",
    pricePer: "ngày",
    priceDisplay: "865K/ngày",
    priceDiscount: "512K giá giờ",
    isFavorite: true
  },
  {
    name: "Porsche 911 GT3 R rennsport",
    image: "/cars/image 2.png",
    price: 585000,
    oldPrice: 600000,
    transmission: "Số tự động",
    seats: 2,
    fuel: "Dầu Diesel",
    location: "Quận Sơn Trà, Đà Nẵng",
    rating: 3.0,
    trips: 37,
    description: "Xe đua chuyên nghiệp, mạnh mẽ và cá tính.",
    badge: "37 chuyến",
    pricePer: "ngày",
    priceDisplay: "585K/ngày",
    priceDiscount: "451K giá giờ",
    isFavorite: false
  },
  {
    name: "SUZUKI XL7 2021",
    image: "/cars/Suzuki 1.png",
    price: 865000,
    oldPrice: 900000,
    transmission: "Số tự động",
    seats: 7,
    fuel: "Xăng",
    location: "Quận Sơn Trà, Đà Nẵng",
    rating: 5.0,
    trips: 37,
    description: "Xe gia đình rộng rãi, tiết kiệm nhiên liệu.",
    badge: "37 chuyến",
    pricePer: "ngày",
    priceDisplay: "865K/ngày",
    priceDiscount: "512K giá giờ",
    isFavorite: false
  },
  {
    name: "Lamborghini SC18 ALSTON",
    image: "/cars/image 4.png",
    price: 1486500,
    oldPrice: 1600000,
    transmission: "Số sàn",
    seats: 2,
    fuel: "Xăng",
    location: "Quận Cẩm Lệ, Đà Nẵng",
    rating: 5.0,
    trips: 37,
    description: "Siêu xe thể thao đỉnh cao, thiết kế độc đáo.",
    badge: "37 chuyến",
    pricePer: "ngày",
    priceDisplay: "1486K/ngày",
    priceDiscount: "989K giá giờ",
    isFavorite: true
  }
];

export default vehicles;